import { ICard } from '../store/types/interfaces/ICard';

export const cardMap: Record<string, ICard> = {
  AB: {
    value: 'A',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/A.png',
    cardId: 'AB',
  },
  '2B': {
    value: '2',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/2.png',
    cardId: '2B',
  },
  '3B': {
    value: '3',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/3.png',
    cardId: '3B',
  },
  '4B': {
    value: '4',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/4.png',
    cardId: '4B',
  },
  '5B': {
    value: '5',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/5.png',
    cardId: '5B',
  },
  '6B': {
    value: '6',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/6.png',
    cardId: '6B',
  },
  '7B': {
    value: '7',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/7.png',
    cardId: '7B',
  },
  '8B': {
    value: '8',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/8.png',
    cardId: '8B',
  },
  '9B': {
    value: '9',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/9.png',
    cardId: '9B',
  },
  '10B': {
    value: '10',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/10.png',
    cardId: '10B',
  },
  JB: {
    value: 'J',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/J.png',
    cardId: 'JB',
  },
  QB: {
    value: 'Q',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/Q.png',
    cardId: 'QB',
  },
  KB: {
    value: 'K',
    color: 'B',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/blue/K.png',
    cardId: 'KB',
  },
  AG: {
    value: 'A',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/A.png',
    cardId: 'AG',
  },
  '2G': {
    value: '2',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/2.png',
    cardId: '2G',
  },
  '3G': {
    value: '3',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/3.png',
    cardId: '3G',
  },
  '4G': {
    value: '4',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/4.png',
    cardId: '4G',
  },
  '5G': {
    value: '5',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/5.png',
    cardId: '5G',
  },
  '6G': {
    value: '6',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/6.png',
    cardId: '6G',
  },
  '7G': {
    value: '7',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/7.png',
    cardId: '7G',
  },
  '8G': {
    value: '8',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/8.png',
    cardId: '8G',
  },
  '9G': {
    value: '9',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/9.png',
    cardId: '9G',
  },
  '10G': {
    value: '10',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/10.png',
    cardId: '10G',
  },
  JG: {
    value: 'J',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/J.png',
    cardId: 'JG',
  },
  QG: {
    value: 'Q',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/Q.png',
    cardId: 'QG',
  },
  KG: {
    value: 'K',
    color: 'G',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/green/K.png',
    cardId: 'KG',
  },
  AR: {
    value: 'A',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/A.png',
    cardId: 'AR',
  },
  '2R': {
    value: '2',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/2.png',
    cardId: '2R',
  },
  '3R': {
    value: '3',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/3.png',
    cardId: '3R',
  },
  '4R': {
    value: '4',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/4.png',
    cardId: '4R',
  },
  '5R': {
    value: '5',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/5.png',
    cardId: '5R',
  },
  '6R': {
    value: '6',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/6.png',
    cardId: '6R',
  },
  '7R': {
    value: '7',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/7.png',
    cardId: '7R',
  },
  '8R': {
    value: '8',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/8.png',
    cardId: '8R',
  },
  '9R': {
    value: '9',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/9.png',
    cardId: '9R',
  },
  '10R': {
    value: '10',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/10.png',
    cardId: '10R',
  },
  JR: {
    value: 'J',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/J.png',
    cardId: 'JR',
  },
  QR: {
    value: 'Q',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/Q.png',
    cardId: 'QR',
  },
  KR: {
    value: 'K',
    color: 'R',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/red/K.png',
    cardId: 'KR',
  },
  AY: {
    value: 'A',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/A.png',
    cardId: 'AY',
  },
  '2Y': {
    value: '2',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/2.png',
    cardId: '2Y',
  },
  '3Y': {
    value: '3',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/3.png',
    cardId: '3Y',
  },
  '4Y': {
    value: '4',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/4.png',
    cardId: '4Y',
  },
  '5Y': {
    value: '5',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/5.png',
    cardId: '5Y',
  },
  '6Y': {
    value: '6',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/6.png',
    cardId: '6Y',
  },
  '7Y': {
    value: '7',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/7.png',
    cardId: '7Y',
  },
  '8Y': {
    value: '8',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/8.png',
    cardId: '8Y',
  },
  '9Y': {
    value: '9',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/9.png',
    cardId: '9Y',
  },
  '10Y': {
    value: '10',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/10.png',
    cardId: '10Y',
  },
  JY: {
    value: 'J',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/J.png',
    cardId: 'JY',
  },
  QY: {
    value: 'Q',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/Q.png',
    cardId: 'QY',
  },
  KY: {
    value: 'K',
    color: 'Y',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/yellow/K.png',
    cardId: 'KY',
  },
  SG: {
    value: 'swap',
    color: 'multi',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/swap.png',
    cardId: 'SG',
  },
  SR: {
    value: 'swap',
    color: 'multi',
    image: 'https://raw.githubusercontent.com/mkoroleva5/blazing-8s-cards/main/swap.png',
    cardId: 'SR',
  },
};
